name = "lianas.org"
license = "MIT"
licenselink = "https://github.com/Liana64/lianas.org/blob/main/LICENSE"
description = "Fork of Gleb Buzin's hugo-dead-simple"
homepage = "https://github.com/Liana64/lianas.org"
tags = [
    "minimal",
]
features = [
  "responsive",
  "single-column",
  "blog",
  "table-of-contents",
  "favicon"
]
min_version = "0.83.0"

[author]
    name = "Liana64, Gleb Buzin"
    homepage = "https://github.com/Liana64"
